由使用者 unknown or anonymous 啟動
Running as SYSTEM
建置中 工作區 C:\pytest
[pytest] $ cmd /c call C:\Windows\TEMP\jenkins10732865971044609407.bat

C:\pytest>C:

C:\pytest>pytest -vs test.py -s -q --alluredir target/allure-results 
============================= test session starts =============================
platform win32 -- Python 3.11.1, pytest-7.2.0, pluggy-1.0.0
rootdir: C:\pytest
plugins: allure-pytest-2.12.0, html-3.2.0, json-report-1.5.0, metadata-2.0.4, testconfig-0.2.0
Hello world112
collected 0 items

============================ no tests ran in 0.01s ============================

C:\pytest>exit 5 
Build step '執行 Windows 批次指令' marked build as failure
[pytest] $ C:\allure-2.20.1\bin\allure.bat generate C:\pytest\target\allure-results -c -o C:\pytest\target\allure-report
Report successfully generated to C:\pytest\target\allure-report
Allure report was successfully generated.
Creating artifact for the build.
Artifact was added to the build.
Finished: FAILURE
